-- MySQL Script generated by MySQL Workbench
-- dom 11 abr 2021 22:15:40 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema templegym
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema templegym
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `templegym` ;
USE `templegym` ;

-- -----------------------------------------------------
-- Table `templegym`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `templegym`.`USER` (
  `DNI` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `active` INT NOT NULL,
  PRIMARY KEY (`DNI`),
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `templegym`.`DIETA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `templegym`.`DIETA` (
  `idDieta` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `grasas` INT(3) NOT NULL,
  `carbohidratos` INT(3) NOT NULL,
  `proteinas` INT(3) NOT NULL,
  `alergenos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDieta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `templegym`.`RUTINA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `templegym`.`RUTINA` (
  `idRUTINA` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `intensidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRUTINA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `templegym`.`PLAN_ENTRENAMIENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `templegym`.`PLAN_ENTRENAMIENTO` (
  `idPLAN_ENTRENAMIENTO` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `objetivo` VARCHAR(45) NOT NULL,
  `precio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPLAN_ENTRENAMIENTO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `templegym`.`USER_has_PLAN_ENTRENAMIENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `templegym`.`USER_has_PLAN_ENTRENAMIENTO` (
  `USER_DNI` INT NOT NULL,
  `PLAN_ENTRENAMIENTO_idPLAN_ENTRENAMIENTO` INT NOT NULL,
  `fecha_inscripcion` DATE NOT NULL,
  PRIMARY KEY (`USER_DNI`, `PLAN_ENTRENAMIENTO_idPLAN_ENTRENAMIENTO`),
  INDEX `fk_USER_has_PLAN_ENTRENAMIENTO_PLAN_ENTRENAMIENTO1_idx` (`PLAN_ENTRENAMIENTO_idPLAN_ENTRENAMIENTO` ASC) VISIBLE,
  INDEX `fk_USER_has_PLAN_ENTRENAMIENTO_USER_idx` (`USER_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_USER_has_PLAN_ENTRENAMIENTO_USER`
    FOREIGN KEY (`USER_DNI`)
    REFERENCES `templegym`.`USER` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_has_PLAN_ENTRENAMIENTO_PLAN_ENTRENAMIENTO1`
    FOREIGN KEY (`PLAN_ENTRENAMIENTO_idPLAN_ENTRENAMIENTO`)
    REFERENCES `templegym`.`PLAN_ENTRENAMIENTO` (`idPLAN_ENTRENAMIENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `templegym`.`PLAN_ENTRENAMIENTO_has_RUTINA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `templegym`.`PLAN_ENTRENAMIENTO_has_RUTINA` (
  `PLAN_ENTRENAMIENTO_idPLAN_ENTRENAMIENTO` INT NOT NULL,
  `RUTINA_idRUTINA` INT NOT NULL,
  PRIMARY KEY (`PLAN_ENTRENAMIENTO_idPLAN_ENTRENAMIENTO`, `RUTINA_idRUTINA`),
  INDEX `fk_PLAN_ENTRENAMIENTO_has_RUTINA_RUTINA1_idx` (`RUTINA_idRUTINA` ASC) VISIBLE,
  INDEX `fk_PLAN_ENTRENAMIENTO_has_RUTINA_PLAN_ENTRENAMIENTO1_idx` (`PLAN_ENTRENAMIENTO_idPLAN_ENTRENAMIENTO` ASC) VISIBLE,
  CONSTRAINT `fk_PLAN_ENTRENAMIENTO_has_RUTINA_PLAN_ENTRENAMIENTO1`
    FOREIGN KEY (`PLAN_ENTRENAMIENTO_idPLAN_ENTRENAMIENTO`)
    REFERENCES `templegym`.`PLAN_ENTRENAMIENTO` (`idPLAN_ENTRENAMIENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PLAN_ENTRENAMIENTO_has_RUTINA_RUTINA1`
    FOREIGN KEY (`RUTINA_idRUTINA`)
    REFERENCES `templegym`.`RUTINA` (`idRUTINA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `templegym`.`PLAN_ENTRENAMIENTO_has_DIETA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `templegym`.`PLAN_ENTRENAMIENTO_has_DIETA` (
  `PLAN_ENTRENAMIENTO_idPLAN_ENTRENAMIENTO` INT NOT NULL,
  `DIETA_idDieta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PLAN_ENTRENAMIENTO_idPLAN_ENTRENAMIENTO`, `DIETA_idDieta`),
  INDEX `fk_PLAN_ENTRENAMIENTO_has_DIETA_DIETA1_idx` (`DIETA_idDieta` ASC) VISIBLE,
  INDEX `fk_PLAN_ENTRENAMIENTO_has_DIETA_PLAN_ENTRENAMIENTO1_idx` (`PLAN_ENTRENAMIENTO_idPLAN_ENTRENAMIENTO` ASC) VISIBLE,
  CONSTRAINT `fk_PLAN_ENTRENAMIENTO_has_DIETA_PLAN_ENTRENAMIENTO1`
    FOREIGN KEY (`PLAN_ENTRENAMIENTO_idPLAN_ENTRENAMIENTO`)
    REFERENCES `templegym`.`PLAN_ENTRENAMIENTO` (`idPLAN_ENTRENAMIENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PLAN_ENTRENAMIENTO_has_DIETA_DIETA1`
    FOREIGN KEY (`DIETA_idDieta`)
    REFERENCES `templegym`.`DIETA` (`idDieta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
